# Generated by Django 5.2.8 on 2026-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act).', null=True, verbose_name='Please Note'),
        ),
    ]
