# Generated by Django 5.2.8 on 2026-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0002_historicalservicerevision_usage_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerevision',
            name='keywords',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='keywords_de',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='keywords',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='keywords_de',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note'),
        ),
    ]
