# Generated by Django 5.2.8 on 2026-01-06 11:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0003_historicalservicerevision_keywords_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_de'], name='service_name_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='service_name_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_de'], name='service_purp_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['purpose_en'], name='service_purp_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acronym'], name='service_acro_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['responsible'], name='service_resp_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='serviceprov_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acronym'], name='serviceprov_acro_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_de'], name='servicerev_desc_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_en'], name='servicerev_desc_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords_de'], name='servicerev_kw_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords_en'], name='servicerev_kw_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['requirements_de'], name='servicerev_req_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['requirements_en'], name='servicerev_req_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['usage_information_de'], name='servicerev_uinf_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['usage_information_en'], name='servicerev_uinf_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details_de'], name='servicerev_det_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details_en'], name='servicerev_det_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['options_de'], name='servicerev_opt_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['options_en'], name='servicerev_opt_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_internal'], name='servicerev_dint_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['version'], name='servicerev_ver_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['eol'], name='servicerev_eol_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_keys'], name='servicerev_skeys_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
