# Generated by Django 5.2.8 on 2026-01-07 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0004_service_service_name_de_gin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the AI search was initiated', verbose_name='Timestamp')),
                ('step1_completed', models.BooleanField(default=False, help_text='Whether the first AI call (initial evaluation) completed successfully', verbose_name='Step 1 completed')),
                ('step2_needed', models.BooleanField(default=False, help_text='Whether detailed service information was requested', verbose_name='Step 2 needed')),
                ('services_requested', models.JSONField(blank=True, help_text='List of service keys requested in step 1 for detailed evaluation in step 2', null=True, verbose_name='Services requested for detailed evaluation')),
                ('services_recommended', models.JSONField(blank=True, help_text='List of service keys recommended to the user in the final response', null=True, verbose_name='Services recommended')),
                ('tokens_used_step1', models.IntegerField(blank=True, help_text='Number of tokens consumed in the first AI call', null=True, verbose_name='Tokens used in step 1')),
                ('tokens_used_step2', models.IntegerField(blank=True, help_text='Number of tokens consumed in the second AI call (if applicable)', null=True, verbose_name='Tokens used in step 2')),
                ('error_occurred', models.BooleanField(default=False, help_text='Whether an error occurred during the search process', verbose_name='Error occurred')),
                ('error_message', models.TextField(blank=True, help_text='Error message if an error occurred (for debugging)', null=True, verbose_name='Error message')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total duration of the search process in seconds', null=True, verbose_name='Duration (seconds)')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the search', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Search Log',
                'verbose_name_plural': 'AI Search Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ServiceCata_timesta_f051fd_idx'), models.Index(fields=['user', '-timestamp'], name='ServiceCata_user_id_34decd_idx')],
            },
        ),
    ]
