# Generated by Django 5.2.8 on 2026-01-08 08:34

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0005_aisearchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerevision',
            name='service_level',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='service_level_de',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AddField(
            model_name='historicalservicerevision',
            name='service_level_en',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='service_level',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='service_level_de',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AddField(
            model_name='servicerevision',
            name='service_level_en',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations.', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='name_de',
            field=models.CharField(max_length=80, null=True, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='purpose',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='purpose_de',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', null=True, verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='purpose_en',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', null=True, verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='description',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='description_de',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', null=True, verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='description_en',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', null=True, verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details_de',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details_en',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='keywords',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='keywords_de',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options_de',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options_en',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements_de',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_de',
            field=models.CharField(max_length=80, null=True, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Name (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='purpose',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='purpose_de',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', null=True, verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='purpose_en',
            field=models.TextField(help_text='Why is this service offered? What is the intended particular benefit for the user? (brief description only)', null=True, verbose_name='Main purpose / added value of this service (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='description',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='description_de',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', null=True, verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='description_en',
            field=models.TextField(help_text='Self-contained service description. Please avoid links to external sources, if possible.', null=True, verbose_name='Service description (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details_de',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details_en',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable.  May contain links to external sources.', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='keywords',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='keywords_de',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Additional keywords for fulltext search (words separated by spaces). These keywords are used for searching but not visible to users.', null=True, verbose_name='Search keywords (search)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options_de',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options_en',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent.', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements_de',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description.', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['service_level_de'], name='servicerev_slvl_de_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='servicerevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['service_level_en'], name='servicerev_slvl_en_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
