# Generated by Django 5.2.10 on 2026-01-21 11:45

import ServiceCatalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0006_historicalservicerevision_service_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='contact',
            field=models.EmailField(blank=True, default=ServiceCatalogue.models.get_default_helpdesk_email, help_text='Email address which should be used for service requests. If possible helpdesk or other institutional email address, if not applicable also personal email adresses can be used (but might require effort in maintenance).', max_length=80, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='contact',
            field=models.EmailField(blank=True, default=ServiceCatalogue.models.get_default_helpdesk_email, help_text='Email address which should be used for service requests. If possible helpdesk or other institutional email address, if not applicable also personal email adresses can be used (but might require effort in maintenance).', max_length=80, null=True, verbose_name='Contact Email'),
        ),
    ]
