# Generated by Django 5.2.11 on 2026-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCatalogue', '0007_alter_historicalservicerevision_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='description_internal',
            field=models.TextField(blank=True, help_text='For instance: details on hardware, configuration details, pitfalls, documentation requirements etc. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Internal description / configuration'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details_de',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='details_en',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='eol',
            field=models.TextField(blank=True, help_text='Give some hints what to do with this service at end of life, e.g. which which revision to transfer to or which action to take. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='What should happen at EOL?'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options_de',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='options_en',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements_de',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='requirements_en',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='service_level',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='service_level_de',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='service_level_en',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='historicalservicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='description_internal',
            field=models.TextField(blank=True, help_text='For instance: details on hardware, configuration details, pitfalls, documentation requirements etc. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Internal description / configuration'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details_de',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='details_en',
            field=models.TextField(blank=True, help_text='Detailed description and notes on availability / service levels and support during operation, etc. if applicable. May contain links to external sources. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service details (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='eol',
            field=models.TextField(blank=True, help_text='Give some hints what to do with this service at end of life, e.g. which which revision to transfer to or which action to take. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='What should happen at EOL?'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options_de',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='options_en',
            field=models.TextField(blank=True, help_text='Can be used to harmonize user-specific requirements and wishes, at least to some extent. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Available options (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements_de',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='requirements_en',
            field=models.TextField(blank=True, help_text='Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Requirements for use of service, if any. (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='service_level',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='service_level_de',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='service_level_en',
            field=models.TextField(blank=True, help_text='Service level agreement, availability guarantees, support hours, uptime commitments, and response time expectations. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Service level / SLA (public, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_de',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='usage_information_en',
            field=models.TextField(blank=True, help_text='Important information for using this service, e.g. regarding compliance with data privacy, information security and/or AI regulations (EU AI Act). This text is displayed highlighted in the service description. Supports formatting: **bold**, *italic*, lists (- item / 1. item), URLs (auto-linked), and internal links ([[SERVICE-KEY]]).', null=True, verbose_name='Please Note (public, search, ai)'),
        ),
    ]
