"""apps.py generated by django"""

from django.apps import AppConfig


class ServicecatalogueConfig(AppConfig):
    """generated by django"""

    default_auto_field = "django.db.models.BigAutoField"
    name = "ServiceCatalogue"
